//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_s4e_crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpresa()
        {
            this.tblPessoaEmpresa = new HashSet<tblPessoaEmpresa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CNPJ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPessoaEmpresa> tblPessoaEmpresa { get; set; }
    }
}
