//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_s4e_crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPessoaEmpresa
    {
        public int id { get; set; }
        public Nullable<int> tblPessoa_id { get; set; }
        public Nullable<int> tblEmpresa_id { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblPessoa tblPessoa { get; set; }
    }
}
